spring:
  application:
    name: netflix_clone

  datasource:
    url: jdbc:mysql://localhost:3306/netflix_clone
    username: root
    password: rnldyal01@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: netflixCloneProjectJwtSecretKey2026NetflixCloneProject
  expiration: 3600000